# This property is required to enable AndroidX in your project.
android.useAndroidX=true
# This property is recommended to automatically migrate third-party libraries to AndroidX.
android.enableJetifier=true
# Increase Gradle daemon memory for better performance.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8